[package]
name = "graph"
version = "0.1.0"
authors = ["Stephan Bischoff <stephan.bischoff@digle.net>"]
edition = "2018"


[dependencies]
svg = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"