[package]
name = "day01_1"
version = "0.1.0"
authors = ["Stephan Bischoff <stephan.bischoff.hg@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
