[package]
name = "day06_1"
version = "0.1.0"
authors = ["Stephan Bischoff <stephan.bischoff@digle.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
